export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";


// Post
export const GET_ALL_USER_POST_REQUEST =  "GET_ALL_USER_POST_REQUEST";
export const GET_ALL_USER_POST_REQUEST_FAIL =  "GET_ALL_USER_POST_REQUEST_FAIL";
export const GET_ALL_USER_POST = "GET_ALL_USER_POST";
export const SHARE_USER_POST_REQUEST = "SHARE_USER_POST_REQUEST";
export const SHARE_USER_POST_SUCCESS = "SHARE_USER_POST_SUCCESS";
export const SHARE_USER_POST_FAILED = "SHARE_USER_POST_FAILED";
export const GET_POST_BY_USERID_REQUEST = "GET_POST_BY_USERID_REQUEST";
export const GET_POST_BY_USERID = "GET_POST_BY_USERID";
export const GET_POST_BY_USERID_REQUEST_FAIL = "GET_POST_BY_USERID_REQUEST_FAIL";

// Feelings
export const SET_FEELING = "SET_FEELING";
export const CLEAR_FEELING = "CLEAR_FEELING";

// Check in
export const SET_LOCATION = "SET_LOCATION";
export const CLEAR_LOCATION = "CLEAR_LOCATION";

// User Profile
export const GET_ALL_USER_PROFILE_REQUEST = "GET_ALL_USER_PROFILE_REQUEST";
export const GET_ALL_USER_PROFILE = "GET_ALL_USER_PROFILE";
export const GET_ALL_USER_PROFILE_REQUEST_FAIL = "GET_ALL_USER_PROFILE_REQUEST_FAIL";
export const  GET_PROFILE_BY_USERID_REQUEST = "GET_PROFILE_BY_USERID_REQUEST";
export const GET_PROFILE_BY_USERID = "GET_PROFILE_BY_USERID";
export const GET_PROFILE_BY_USERID_REQUEST_FAIL = "GET_PROFILE_BY_USERID_REQUEST_FAIL";
export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const SUCCESS_UPDATE_USER_PROFILE = "SUCCESS_UPDATE_USER_PROFILE";
export const FAIL_UPDATE_USER_PROFILE_REQUEST = "FAIL_UPDATE_USER_PROFILE_REQUEST";

// User Images
export const GET_ALL_USER_PROFILE_IMAGES_REQUEST = "GET_ALL_USER_PROFILE_IMAGES_REQUEST";
export const GET_ALL_PROFILE_IMAGES = "GET_ALL_PROFILE_IMAGES"; 
export const GET_ALL_USER_PROFILE_IMAGES_FAIL = "GET_ALL_USER_PROFILE_IMAGES_FAIL"; 
export const GET_ALL_USER_COVER_IMAGES_REQUEST = "GET_ALL_USER_COVER_IMAGES_REQUEST";
export const GET_ALL_COVER_IMAGES = "GET_ALL_COVER_IMAGES"; 
export const GET_ALL_USER_COVER_IMAGES_FAIL = "GET_ALL_USER_COVER_IMAGES_FAIL"; 

export const UPDATE_USER_PHOTO_REQUEST = "UPDATE_USER_PHOTO_REQUEST";
export const UPDATE_USER_PHOTO_SUCCESS = "UPDATE_USER_PHOTO_SUCCESS";
export const UPDATE_USER_PHOTO_FAIL = "UPDATE_USER_PHOTO_FAIL";

export const DELETE_USER_PHOTO_REQUEST = "DELETE_USER_PHOTO_REQUEST";
export const DELETE_USER_PHOTO_SUCCESS = "DELETE_USER_PHOTO_SUCCESS";
export const DELETE_USER_PHOTO_FAIL = "DELETE_USER_PHOTO_FAIL";


// Academic 

export const UPDATE_ACADEMIC_REQUEST = "UPDATE_ACADEMIC_REQUEST";
export const UPDATE_ACADEMIC_SUCCESS = "UPDATE_ACADEMIC_SUCCESS";
export const UPDATE_ACADEMIC_FAIL = "UPDATE_ACADEMIC_FAIL";

export const ADD_ACADEMIC_REQUEST = "ADD_ACADEMIC_REQUEST";
export const ADD_ACADEMIC_SUCCESS = "ADD_ACADEMIC_SUCCESS";
export const ADD_ACADEMIC_FAIL = "ADD_ACADEMIC_FAIL";

export const DELETE_ACADEMIC_REQUEST = "DELETE_ACADEMIC_REQUEST";
export const DELETE_ACADEMIC_SUCCESS =  "DELETE_ACADEMIC_SUCCESS"
export const DELETE_ACADEMIC_FAIL = "DELETE_ACADEMIC_FAIL";

export const GET_ACADEMIC_REQUEST = "GET_ACADEMIC_REQUEST";
export const GET_ACADEMIC_SUCCESS = "GET_ACADEMIC_SUCCESS";
export const GET_ACADEMIC_FAIL = "GET_ACADEMIC_FAIL";


// Work

export const GET_WORK_REQUEST = "GET_WORK_REQUEST";
export const GET_WORK_SUCCESS = "GET_WORK_SUCCESS";
export const GET_WORK_FAIL = "GET_WORK_FAIL";

export const UPDATE_WORK_REQUEST = "UPDATE_WORK_REQUEST";
export const UPDATE_WORK_SUCCESS = "UPDATE_WORK_SUCCESS";
export const UPDATE_WORK_FAIL = "UPDATE_WORK_FAIL";

export const ADD_WORK_REQUEST = "ADD_WORK_REQUEST";
export const ADD_WORK_SUCCESS =  "ADD_WORK_SUCCESS";
export const ADD_WORK_FAIL = "ADD_WORK_FAIL";

export const DELETE_WORK_REQUEST = "DELETE_WORK_REQUEST";
export const DELETE_WORK_SUCCESS =  "DELETE_WORK_SUCCESS";
export const DELETE_WORK_FAIL = "DELETE_WORK_FAIL";

// Friend Request
export const ADD_FRIEND_REQUEST = "ADD_FRIEND_REQUEST";
export const ADD_FRIEND = "ADD_FRIEND";
export const ADD_FRIEND_REQUEST_FAIL = "ADD_FRIEND_REQUEST_FAIL";

export const GET_FRIEND_REQUEST_USERS_REQUEST = "GET_FRIEND_REQUEST_USERS_REQUEST";
export const GET_FRIEND_REQUESTED_USERS = "GET_FRIEND_REQUESTED_USERS";
export const GET_FRIEND_REQUEST_USERS_FAIL = "GET_FRIEND_REQUEST_USERS_FAIL";

export const CONFIRMED_FRIEND_REQUEST_USERS_REQUEST = "CONFIRMED_FRIEND_REQUEST_USERS_REQUEST";
export const CONFIRMED_FRIEND_REQUEST = "CONFIRMED_FRIEND_REQUEST";
export const CONFIRMED_FRIEND_REQUEST_USERS_FAIL = "CONFIRMED_FRIEND_REQUEST_USERS_FAIL";

export const DELETE_FRIEND_REQUEST_USERS_REQUEST = "DELETE_FRIEND_REQUEST_USERS_REQUEST";
export const DELETE_FRIEND_REQUEST = "DELETE_FRIEND_REQUEST";
export const DELETE_FRIEND_REQUEST_USERS_FAIL = "DELETE_FRIEND_REQUEST_USERS_FAIL";

export const GET_PENDING_FRIEND_REQUEST = "GET_PENDING_FRIEND_REQUEST";
export const GET_PENDING_FRIEND_REQUEST_SUCCESS = "GET_PENDING_FRIEND_REQUEST_SUCCESS";
export const GET_PENDING_FRIEND_REQUEST_FAIL = "GET_PENDING_FRIEND_REQUEST_FAIL";

export const GET_ALL_USER_FRIENDS_REQUEST = "GET_ALL_USER_FRIENDS_REQUEST";
export const GET_ALL_USER_FRIENDS_SUCCESS = "GET_ALL_USER_FRIENDS_SUCCESS";
export const GET_ALL_USER_FRIENDS_FAIL = "GET_ALL_USER_FRIENDS_FAIL";